### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by LiamOSullivan** [LiamOSullivan/bcd-dd-v2#126]
Following error both on localhost and remote:

{"error":{"code":"CERT_HAS_EXPIRED"},"level":"error","message":"uncaughtException: certificate has expired\nError: certificate has expired\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)","stack":"Error: certificate has expired\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)","exception":true,"date":"Thu Jul 18 2019 11:15:00 GMT+0100 (Irish Standard Time)","process":{"pid":5917,"uid":501,"gid":20,"cwd":"/Users/losullivan/Documents/repos/DublinDashboard_v2_mvp/bcd-dd-v2","execPath":"/usr/local/bin/node","version":"v10.12.0","argv":["/usr/local/bin/node","/Users/losullivan/Documents/repos/DublinDashboard_v2_mvp/bcd-dd-v2/bin/www"],"memoryUsage":{"rss":60190720,"heapTotal":30945280,"heapUsed":24716248,"external":24121687}},"os":{"loadavg":[1.947265625,2.166015625,2.19775390625],"uptime":783839},"trace":[{"column":34,"file":"_tls_wrap.js","function":"TLSSocket.onConnectSecure","line":1049,"method":"onConnectSecure","native":false},{"column":13,"file":"events.js","function":"TLSSocket.emit","line":182,"method":"emit","native":false},{"column":8,"file":"_tls_wrap.js","function":"TLSSocket._finishInit","line":631,"method":"_finishInit","native":false}]}

**Comment by LiamOSullivan** [comment]
Tried npm update (global and local) - no fix (localhost)
