### ISSUE TITLE
MVP-housing: Data load error on landing page

### ISSUE THREAD

**Issue by LiamOSullivan** [LiamOSullivan/bcd-dd-v2#19]
Following data fails to load causing no traces on landing page cards:

Failed to load resource: the server responded with a status of 404 (Not Found)
d3.js:5845 
Uncaught (in promise) Error: 404 Not Found
    at responseJson (d3.js:5845)
/data/Transport/traveltimes.json:1 

Failed to load resource: the server responded with a status of 404 (Not Found)
d3.js:5845 

Uncaught (in promise) Error: 404 Not Found
    at responseJson (d3.js:5845)

**Comment by LiamOSullivan** [comment]
Server error: 

2019-05-14T09:30:16  Welcome, you are now connected to log-streaming service.
2019-05-14T09:30:00.033088974Z: [ERROR]      at require (internal/modules/cjs/helpers.js:20:18)2019-05-14T09:30:00.033092374Z: [ERROR]      at Task.execution (/home/site/wwwroot/app.js:149:19)2019-05-14T09:30:00.033095474Z: [ERROR]      at Promise (/node_modules/node-cron/src/task.js:52:23)2019-05-14T09:30:00.033098774Z: [ERROR]      at new Promise (<anonymous>)2019-05-14T09:30:00.033102074Z: [ERROR]      at Task.update (/node_modules/node-cron/src/task.js:50:7)2019-05-14T09:30:00.033105374Z: [ERROR]      at Timeout.ScheduledTask.task [as _onTimeout] (/node_modules/node-cron/src/scheduled-task.js:86:10)2019-05-14T09:30:00.033108674Z: [ERROR]      at ontimeout (timers.js:425:11)2019-05-14T09:30:00.033120074Z: [ERROR]      at tryOnTimeout (timers.js:289:5)2019-05-14T09:30:00.033123974Z: [ERROR]      at listOnTimeout (timers.js:252:5)
2019-05-14T09:30:44

**Comment by LiamOSullivan** [comment]
Fixed with commit d695943113aed162d731d4cceb149a79b8878a9f
